#! /usr/bin/bash


# add the file to the path in order to be able to run it as an oridnary command (without indicating the file script's path with ./ for example)
cp ./go2web /usr/local/bin/

./hi $@
#go run main.go $@